version: "3.7"

services:
  app:
    build: .
    container_name: "application"
    ports:
      - 3479:3479
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongoNetwork
      - nginxNetwork

  nginx:
    image: nginx:latest
    container_name: "nginx"
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - app
    networks:
      - nginxNetwork

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    env_file:
      - ./docker.env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - 27017:27017
    networks:
      - mongoNetwork
    command: mongod --auth --storageEngine wiredTiger --dbpath /data/db

networks:
  mongoNetwork:
  nginxNetwork:
