version: "2"

services:
  app:
    build: .
    container_name: "application"
    ports:
      - 3479:3479
    restart: unless-stopped
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - privateNetwork

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - 27017:27017
    networks:
      - privateNetwork
    command: mongod --auth --storageEngine wiredTiger --dbpath /data/db

networks:
  privateNetwork:



    #docker-compose up --build --force-recreate