version: "2"

services:
  app:
    build: .
    container_name: "vajari"
    ports:
      - 3479:3479
    restart: unless-stopped
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - advertiseNetwork

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: unless-stopped
    env_file:
      - docker.env
    environment:
      - MONGO_DATE_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - advertiseNetwork
    command: mongod

networks:
  advertiseNetwork:
